### ISSUE TITLE
How to reuse code

### ISSUE THREAD

**Issue by jvcsw** [iantrich/config-template-card#111]
Hi,

congratulations for this card, I like it.

I have a doubt/feature:

Could you tell me if is possible reuse (no copy) the getTemperatureTheme function in other temperature card?

Thanks

  - type: custom:config-template-card
    variables:
      getTemperatureTheme: |
        temp => {
          if (temp < 5 || temp > 30) {
              return 'Dark - Orange';
          }
          if (temp < 1 || temp > 35) {
            return 'Dark - Red';
          }
          return '';
        }
      currentTemp: states['sensor.wx_temperature'].state
    entities:
      - sensor.wx_temperature
    card:
      type: entity
      entity: sensor.wx_temperature
      name: Temperature
      theme: ${ getTemperatureTheme(currentTemp) }

**Comment by ildar170975** [comment]
Solution was provided here:
https://community.home-assistant.io/t/create-a-new-custom-card-from-an-existing-custom-card/460810/3?u=ildar_gabdullin
The issue may be closed by @jvcsw.
