### ISSUE TITLE
Secrets support

### ISSUE THREAD

**Issue by alanmilinovic** [iantrich/config-template-card#116]
Hi, is it possible to use secret. I tried following in my iframe card but it is not working:

```
type: custom:config-template-card
entities:
  - input_select.password
card:
  type: iframe
  style: |
    #root {
      height: calc(100vh - 48.5px);
      padding-top: 0 !important;
    }
  url: >-
    ${'http://'+window.location.hostname+':20530/sysmanager.php?username=amilino&password='+secret! password}
```

This is working alternative, but not what I wanted:

```
url: >-
    ${'http://'+window.location.hostname+':20530/sysmanager.php?username=amilino&password='+states['input_select.password'].state}
```

**Comment by alanmilinovic** [comment]
Thank you for your reply, but I lost you somewhere in the middle. :)

I stayed with using alternative solution in the end with input.select and used secret there.

```
password:
  name: Password
  options:
    - !secret 1nuc_root_password
  icon: mdi:account-key
```

**Comment by ildar170975** [comment]
1. The card still may be used for some cases. I am still using it.
Yes, there are issues which are not even reviewed by the card's author during a very long time - that is why I am saying that the card is abandoned.

2. As for alternatives - it depends on what you need. Some results may be achieved by other custom cards like `template-entity-row`, some by using template sensors, some - by using templates with card-mod.
In you particular case I suggest you to use a template sensor for the `url` option.

**Comment by ildar170975** [comment]
> but I lost you somewhere in the middle. :)

no problem)

**Comment by alanmilinovic** [comment]
Isn't it too much to use template sensor for a static value? I am trying to avoid filling database with history records.

**Comment by ildar170975** [comment]
DB is filled mainly by CHANGING values.
