### ISSUE TITLE
Variables with addition are adding decimal places and not whole numbers

### ISSUE THREAD

**Issue by ghallford** [iantrich/config-template-card#120]
**Checklist:**

- [ X] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue: **
1.3.6

**Last working release (if known):**

**Browser and Operating System: **
Chrome, Windows 11

**Description of problem:**
I am trying to put in a gauge graph, where there is a yellow and red for to low and yellow and red for too high. The low part work fine but the high part, using the addition doesn't add properly.

If I set "input_number.probe4targettemp" to 250. Expected vars are:

vars[0] = 230
vars[1] = 210
vars[2] = 270
vars[3] = 290

What I am getting is this:

vars[0] = 230
vars[1] = 210
vars[2] = 250.020
vars[3] = 250.040

Why???? Addition is adding decimal places and not whole numbers

Here is the yaml.

  - type: custom:config-template-card
    variables:
      - states['input_number.probe4targettemp'].state - 20
      - states['input_number.probe4targettemp'].state - 40
      - states['input_number.probe4targettemp'].state + 20
      - states['input_number.probe4targettemp'].state + 40
    entities:
      - sensor.probe4temp
      - input_number.probe4targettemp
    card:
      type: gauge
      entity: sensor.probe4temp
      name: Ambient Temp
      needle: true
      min: 0
      max: 500
      segments:
        - from: 0
          color: '#db4437'
        - from: ${vars[1]}
          color: '#ffa600'
        - from: ${vars[0]}
          color: '#43a047'
        - from: ${vars[2]}
          color: '#ffa600'
        - from: ${vars[3]}
          color: '#db4437'

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by ildar170975** [comment]
Do not think this is a bug. 
Each variable is a STRING. 
Using “+” causes concatenating “250.0” and “40” which gives “250.040”.
Using “-“ causes converting both values to integers and gives “210”. 
To avoid any issues I usually use something like:
parseFloat(states['input_number.probe4targettemp'].state) - 20

**Comment by ildar170975** [comment]
An answer was provided, no further remarks were added.
Closing as solved.
