### ISSUE TITLE
Browser console warning: The main 'lit-element' module entrypoint is deprecated

### ISSUE THREAD

**Issue by RedNo7** [iantrich/config-template-card#134]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.3.6

**Last working release (if known):**
n/a

**Browser and Operating System:**
Safari 16.6
MacOS 13.6
...same warning in Firefox.

**Description of problem:**
The browser (Safari, Firefox) console shows the following warning:
> The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.

**Javascript errors shown in the web inspector (if applicable):**

**Additional information:**

**Comment by ildar170975** [comment]
Duplicate https://github.com/iantrich/config-template-card/issues/91
