### ISSUE TITLE
Update based on time?

### ISSUE THREAD

**Issue by deviantintegral** [iantrich/config-template-card#137]
Hello, thanks for this card! I'm currently using it so that I can add a query string to picture cards so they bust caches every hour.

At a quick glance, it appears that the `entities` configuration value is required because that's what the card uses to determine if it should rerender the card. In my case, I've hacked this by attaching it to an entity that updates often (in this case, the WLAN traffic stats). Is there some other way I missed to make the card re-evaluate based on a schedule? Or am I just doing this whole use case wrong?

**Comment by ildar170975** [comment]
Currently only a monitored entity's change may force the card to update itself.

**Comment by ildar170975** [comment]
Can we close the issue then?
