### ISSUE TITLE
Source map error - Source Map URL: custom-sonos-card.js.map

### ISSUE THREAD

**Issue by johntdyer** [iantrich/config-template-card#145]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
7.11.2

**Last working release (if known):**

**Browser and Operating System:**
Firefox OSX 129.0 (64-bit)

**Description of problem:**

Noticed this warning in my logs, not sure how to resolve it 

**Javascript errors shown in the web inspector (if applicable):**

```
Source map error: request failed with status 404 Resource URL: https://xxxxxx/hacsfiles/custom-sonos-card/custom-sonos-card.js?hacstag=4494168166101 Source Map URL: custom-sonos-card.js.map
```

**Additional information:**

**Comment by ildar170975** [comment]
> custom-sonos-card

Wrong repo.
Please close & check in the proper card's repo.

**Comment by johntdyer** [comment]
damn, sorry, was seeing a few of these and opening tickets... guess I got mixed up :)

**Comment by johntdyer** [comment]
Opened correctly in the correct repo :) 

https://github.com/punxaphil/custom-sonos-card/issues/441

sorry for the mixup
