### ISSUE TITLE
Error in chrome consolle - deprecate component?

### ISSUE THREAD

**Issue by riddik14** [iantrich/config-template-card#146]
The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonime) @ config-template-card.js?hacstag=172177543136:329

**Comment by ildar170975** [comment]
Duplicate of https://github.com/iantrich/config-template-card/issues/91
