### ISSUE TITLE
Help Requested: Variable as Dynamic Threshold for apexcharts-card

### ISSUE THREAD

**Issue by MarcelMertens** [iantrich/config-template-card#151]
Hi,
i try to use the config-template-card for dynamic threshold coloring of the apexcharts card.

I have an input_number.evcc_energyprice_limit state which i'd like to use for the threshold.

`
type: custom:config-template-card
entities:
  - input_number.evcc_energyprice_limit
variables:
  EVCC_LIMIT: states['input_number.evcc_energyprice_limit'].state
`

When using `${ EVCC_LIMIT }` in apexcharts-card config i receive the following error
`value.series[0].color_threshold[0].value is not a number`

My complete configuration.
As you can see i also put `${ EVCC_LIMIT }` as the title which is working fine

`type: custom:config-template-card
entities:
  - input_number.evcc_energyprice_limit
variables:
  EVCC_LIMIT: states['input_number.evcc_energyprice_limit'].state
card:
  type: custom:apexcharts-card
  experimental:
    color_threshold: true
  apex_config:
    chart:
      height: 180px
  header:
    show: true
    title: ${ EVCC_LIMIT }
    show_states: true
    colorize_states: true
  hours_12: false
  graph_span: 36h
  now:
    show: true
    color: red
    label: Jetzt
  span:
    start: hour
    offset: "-6h"
  yaxis:
    - id: EUR
      decimals: 2
      min: 0.15
  series:
    - entity: sensor.tibber_prices
      type: column
      stroke_width: 0
      float_precision: 3
      curve: stepline
      opacity: 0.75
      color_threshold:
        - value: ${ EVCC_LIMIT }
          color: red
        - value: 0
          color: green
      show:
        legend_value: false
        extremas: true
        in_header: false
      extend_to: now
      name: Strompreis
      unit: €
      yaxis_id: EUR
      data_generator: |
        var today = entity.attributes.today.map((record, index) => {
                return [record.startsAt, record.total];
              });
        var tomorrow = entity.attributes.tomorrow.map((record, index) => {
                return [record.startsAt, record.total];
              });

        return today.concat(tomorrow);
    - entity: sensor.current_energy_price
      name: Aktueller Strompreis
      float_precision: 2
      show:
        extremas: false
        legend_value: true
        in_header: true
        in_chart: false
      color_threshold:
        - value: 0
          color: DodgerBlue
        - value: 0.2
          color: lightgreen
        - value: 0.25
          color: green
        - value: 0.3
          color: yellow
        - value: 0.32
          color: gold
        - value: 0.35
          color: orange
        - value: 0.38
          color: tomato
        - value: 0.4
          color: red
`

![image](https://github.com/user-attachments/assets/d0ddf1a6-9db7-4ced-9952-1007444ba1dc)
![image](https://github.com/user-attachments/assets/2201f50d-76a5-497f-909e-179cc99b9358)

**Comment by ildar170975** [comment]
Sorry, please use github for reporting bugs & proposing feature requests.
Other questions should be posted in the main dedicated thread: https://community.home-assistant.io/t/100-templatable-lovelace-configurations/105241
Also, using `config-template-card` for graph cards is not the best way:
1. If an entity used for building a graph is not defined as "monitored" in an `entities` option - the graph will be not redrawn realtime.
2. Otherwise - the whole card will be redrawn which may cause flickering & other undesired transitions.
