### ISSUE TITLE
Force entities to be specified or debounce re-renders

### ISSUE THREAD

**Issue by balloob** [iantrich/config-template-card#16]
If this card re-renders on every state change, it is re-rendering like crazy on big instances. This causes browsers to eat battery and kills performance.

See also https://github.com/home-assistant/home-assistant/issues/23938

I suggest that either re-renders are debounced if no entities are specified (ie max render once a second) or that leaving entities to track out of your config will cause it to not re-render at all.

**Comment by iantrich** [comment]
Resolved in https://github.com/iantrich/config-template-card/releases/tag/1.0.7
