### ISSUE TITLE
Firefox stops responding. 

### ISSUE THREAD

**Issue by tomlut** [iantrich/config-template-card#18]
**Checklist:**

- [ x ] I updated to the latest version available
- [ x ] I cleared the cache of my browser

**Release with the issue:**
config-template-card 1.0.8

**Last working release (if known):**
Not known
**Browser and Operating System:**
Firefox 70.0.1 64bit, Windows 10 pro1903 (build 18362.418)

**Description of problem:**
Firefox stops responding after a short time. Error in the console is shown below:

![Untitled](https://user-images.githubusercontent.com/10679300/69401876-526f7a80-0d4a-11ea-8105-bc5382927e34.png)

Chrome appears to ignore the error.

**Javascript errors shown in the web inspector (if applicable):**
As per screenshot above.
```

```

**Additional information:**

**Comment by iantrich** [comment]
Still an issue?

**Comment by tomlut** [comment]
Yes still getting the error. Though it no longer seems to be halting the browser. 

![Untitled](https://user-images.githubusercontent.com/10679300/84105239-24752d80-aa31-11ea-950c-3b8fa2f11fb8.png)

**Comment by ildar170975** [comment]
@tomlut 
Are you still having this issue?

**Comment by tomlut** [comment]
I no longer use the card.

**Comment by ildar170975** [comment]
Closing then...
