### ISSUE TITLE
Entities icon change does not work

### ISSUE THREAD

**Issue by theHasp** [iantrich/config-template-card#29]
I just want to change the icon based on the state ... so far so simple ...

It seems like there is a sanitizer running over the json removing all the " which breaks the condition

So when I store

` icon: "${states[cover.fenster_sued].state === 'open' ? 'mdi:window-shutter-open' : 'mdi:window-shutter' }"`

will be automatically replaced by 

```
icon: >-
        ${states[cover.fenster_sued].state === 'open' ?
        'mdi:window-shutter-open' : 'mdi:window-shutter' }
```

which of course breaks the whole thing

What am I do wrong ....
THANKS

**Comment by iantrich** [comment]
that's not breaking it, your lack of quotes on `cover.fenster_sued` breaks it

**Comment by theHasp** [comment]
THANKS ... that was easy :-)
AND DEFINITELY NOT A BUG
