### ISSUE TITLE
0.110 - Error - t.setConfig is not a function config-template-card

### ISSUE THREAD

**Issue by rednus** [iantrich/config-template-card#31]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
1.1.2
**Last working release (if known):**

**Browser and Operating System:**
Chrome - Windows 10

**Description of problem:**
type: 'custom:config-template-card' returns 'No card defined' error

**Javascript errors shown in the web inspector (if applicable):**
config-template-card Error: No card defined
    at HTMLElement.setConfig (config-template-card.js?v=1.1.2:3225)
    at s (hui-weather-forecast-card.ts:39)
    at hui-weather-forecast-card.ts:39
    at l (hui-weather-forecast-card.ts:39)
    at Ht (hui-weather-forecast-card.ts:39)
    at HTMLElement.value (search-input.ts:17)
    at HTMLElement.value (search-input.ts:17)
    at HTMLElement.performUpdate (bootstrap:2)
    at HTMLElement._enqueueUpdate (bootstrap:2)

hui-plant-status-card
Uncaught (in promise) TypeError: t.setConfig is not a function
config-template-card

```

```

**Additional information:**

**Comment by iantrich** [comment]
https://github.com/home-assistant/frontend/pull/5944

**Comment by petergerdes** [comment]
@iantrich With updated frontend, it's still happening :(

**Comment by rednus** [comment]
I have updated to 0.110.2  and it fixed for me..

**Comment by petergerdes** [comment]
Hmm, updated to 0.110.3 and still same errors. Multiple browser, cleared cache.
