### ISSUE TITLE
I'm not quite clear on what constructs are allowing and where?

### ISSUE THREAD

**Issue by deepcoder** [iantrich/config-template-card#48]
I'm not quite clear on what constructs are allowing and where?

Q1: what language is this, where can I find docs on syntax and operators:

`LIGHT_STATE === 'on' ? 'glance' : 'entities'`

Q2: 'All templates must be enclosed by ${}'

When you say 'template', is this the standard HA templating? Is Jinja allowed?

Any examples you might point me to would be great.

Thanks for your work and help!

Dave

**Comment by iantrich** [comment]
Per the first line of the [ReadMe](https://github.com/iantrich/config-template-card/blob/master/README.md#config-template-card-card), this is JavaScript
