### ISSUE TITLE
Cannot automate element position

### ISSUE THREAD

**Issue by lativl** [iantrich/config-template-card#56]
**Release with the issue:**
HA  - 0.118.3

**Browser and Operating System:**
Any

**Description of problem:**

I'm trying to implement dynamic repositioning of the element but it looks like templating doesn't work within **style** block. Can it be fixed or workarounded somehow?

**Code example (hardcoded variable to simplify the case):**
  - type: 'custom:config-template-card'
    variables:
      - ("50"+"%") #expected top position      
    entities:
      - input_number.test_point
    element:
      type: 'custom:text-element'
      text: '${vars[0]}'
      style:
        top: 0
        left: 0
    style:
      color: white
      top: '${vars[0]}' #expected top position 50% but it doesn't work 
      left: 12%
      width: 10%

![image](https://user-images.githubusercontent.com/34886340/101741413-b0e0d580-3ad2-11eb-9e51-44d2e6028a33.png)

**Comment by iantrich** [comment]
that's because the style is not rendered by the card, you're likely using card-mod, in which case use the tempting specified in those docs
