### ISSUE TITLE
Allow templating styles

### ISSUE THREAD

**Issue by shbatm** [iantrich/config-template-card#57]
**Is your feature request related to a problem? Please describe.**
Changing the colors of the icons for a Picture Entities card requires changing them in the `style:` section but it doesn't appear that you can use the templates in this section.

**Describe the solution you'd like**
Add support for templates in the style section.

**Describe alternatives you've considered**
Using state icons from the built-in Picture Elements state-icon type. This won't work for setting different colors based on a custom sensor's state, which doesn't have an "on" state.

**Additional context**
Let me know if you need more info.

**Comment by iantrich** [comment]
works in 1.3.4
