### ISSUE TITLE
cant find in HACS or find config-template-card.js

### ISSUE THREAD

**Issue by Necrosaurus** [iantrich/config-template-card#59]
hi, looking forward to trying out this addon :)

Unfortunately i cant install it! Please excuse my ignorance, but i have the same issue as another user (config-template-card.js missing #20) that i cant find the file called "config-template-card.js". and i don't understand the answer given that it is "in the release". The closest file i can find is "config-template-card.ts" in the "src" folder. Is this what is meant?

I am running Home Assistant version core-2021.1.5 on a raspberry pi 4 with latest versions of all software,

thank you for your help

**Comment by iantrich** [comment]
It's is in HACS and if you want to download manually it is in the release. 

https://github.com/iantrich/config-template-card/releases

![image](https://user-images.githubusercontent.com/1287159/106364329-d381b480-62f3-11eb-99d0-7ed925cffa33.jpeg)
