### ISSUE TITLE
new state functions are not working

### ISSUE THREAD

**Issue by loki-sft** [iantrich/config-template-card#82]
works:
      variables:
        - states['light.wohn_deckenlampe'].attributes.brightness

but it's depricated

does not work:
      variables:
        - state_attr('light.wohn_deckenlampe', 'brightness')

**Comment by bkr1969** [comment]
Have you looked at [https://github.com/iantrich/config-template-card/issues/79#issuecomment-920399501](https://github.com/iantrich/config-template-card/issues/79#issuecomment-920399501)?  There is a PR that should be merged soon to fix this issue.

**Comment by iantrich** [comment]
This card does not support jinja functions, check the readme
