### ISSUE TITLE
Problems with ctc influence on formatting other elements/cards

### ISSUE THREAD

**Issue by QbaF** [iantrich/config-template-card#83]
Using `config-template-card` has impact on other elements formatting/arrangements.

I have 3 full heigh screen vertical-stack cards. Before using ctc they were placed side by side. Now, that one with ctc, "snap" another vertical-stack card below. I tried to place another card type to check if it is vartical-stack card but other act similary. 

When removing header code:
```
type: custom:config-template-card
entities:
  - ...
card:
```
formatting back to normal.

System:
core-2021.9.7
supervisor-2021.09.4
config-template-card 1.3.4

**Comment by ildar170975** [comment]
Closed as a duplicate
