### ISSUE TITLE
Is it possible to add the name of the currently selected theme?

### ISSUE THREAD

**Issue by majkers** [iantrich/config-template-card#88]
Hello,
is it possible to add the name of the currently selected theme? I would like to change background image depending on it. And my next question is that why I get warning when templating picture-elements card itself? I know that recommended way is to use it as one of the elements but, like I said before, I need to change image of picture-elements card.

**Comment by ildar170975** [comment]
> And my next question is that why I get warning when templating picture-elements card itself?

Do not put absolutely different issues in one issue

**Comment by ildar170975** [comment]
There are 3 different questions here.
As I said - for each question a separate issue should be created.
So far there is no feedback from OP.

> add the name of the currently selected theme?

A name of the currently selected theme is not possible to acquire.
Correct me anyone if you know a way.

> I would like to change background image depending on it

1. It is possible by card-mod which supports jinja.
2. It is possible by using `config-template-card` (although using CTC for the whole picture-elements is not recommended; CTC should be used to [style a single element](https://github.com/iantrich/config-template-card#picture-elements-card-example)).

[Possible solutions posted in HA Community.](https://community.home-assistant.io/t/styling-elements-in-picture-elements-card-a-small-tutorial/315252/17?u=ildar_gabdullin)
