### ISSUE TITLE
Using element or row sections

### ISSUE THREAD

**Issue by MikeTheCleric** [iantrich/config-template-card#89]
Hi! 
From the docs I didn't understand how to use the element and row sections. I still need a card to use them?
In my interface I need to edit an input_datetime to show only the input cell removing the title and the icon badge. 
It is possible?

Thanks in advice

**Comment by ildar170975** [comment]
> In my interface I need to edit an input_datetime to show only the input cell removing the title and the icon badge.
> It is possible?

Simply implemented by `card-mod`

**Comment by iantrich** [comment]
As @ildar170975 said, not something that this card would do.
