### ISSUE TITLE
Documentation, clarify resource section

### ISSUE THREAD

**Issue by jpravetz** [iantrich/config-template-card#98]
The readme says
```
resources:
  - url: /local/config-template-card.js
    type: module
```
If this is meant to be used, it should say what for. If it is meant to be put on the configuration.yaml, it should say so. If it is mean to be put under a lovelace top-level object, it should say so.

**Comment by chrisdothtml** [comment]
Is this even needed? I'm new to HomeAssistant, and it seems where HACS installs this card should already be picked up by HA ([docs](https://developers.home-assistant.io/docs/frontend/custom-ui/custom-card/#:~:text=Create%20a%20new%20file%20in%20your%20Home%20Assistant%20config%20dir%20as%20%3Cconfig%3E/www/content%2Dcard%2Dexample.js%20and%20put%20in%20the%20following%20contents))

**Comment by ildar170975** [comment]
It is clearly said that 2 methods are available, and a link about "installing a plugin" is provided:

![изображение](https://github.com/iantrich/config-template-card/assets/71872483/b0e1ec69-c9b1-4a44-9d0a-5ee824382319)

Why registering a module to install a plugin - is a question beyond this repo.
This should be covered by HA documentation.

>  it seems where HACS installs this card should already be picked up by HA

HACS does what is supposed to be done by a user - copies files to a directory & registers a new resource.
So, when using HACS - there is no need to add a resource manually.
